# Codecov Configuration
# https://docs.codecov.com/docs/codecovyml-reference

coverage:
  precision: 2
  round: down
  range: "70...100"

  status:
    project:
      default:
        target: 80%
        threshold: 2%
        if_ci_failed: error
        # Set to 'informational' to report without blocking PRs
        # Change to 'true' when ready to enforce
        informational: true
    patch:
      default:
        target: 80%
        threshold: 5%
        # New code should meet 80% coverage
        informational: false

comment:
  layout: "header, diff, flags, components, footer"
  behavior: default
  require_changes: true
  require_base: false
  require_head: true

flags:
  unittests:
    paths:
      - api/src/
    carryforward: true

ignore:
  - "**/*.module.ts"
  - "**/*.dto.ts"
  - "**/*.entity.ts"
  - "**/main.ts"
  - "**/index.ts"
  - "**/test/**"
  - "**/node_modules/**"
