export const SCHEMAS: Record<string, string> = {
  workspaces: `
    CREATE TABLE IF NOT EXISTS {database}.workspaces (
      id String,
      name String,
      website String,
      timezone String,
      currency String,
      logo_url Nullable(String),
      timescore_reference UInt32 DEFAULT 60,
      status Enum8('initializing' = 1, 'active' = 2, 'inactive' = 3, 'error' = 4),
      created_at DateTime64(3) DEFAULT now64(3),
      updated_at DateTime64(3) DEFAULT now64(3)
    ) ENGINE = MergeTree()
    ORDER BY id
  `,

  events: `
    CREATE TABLE IF NOT EXISTS {database}.events (
      id UUID DEFAULT generateUUIDv4(),
      session_id String,
      workspace_id String,
      created_at DateTime64(3),
      name LowCardinality(String),
      path String,
      duration UInt64 DEFAULT 0,
      referrer Nullable(String),
      referrer_domain Nullable(String),
      referrer_path Nullable(String),
      is_direct Bool DEFAULT false,
      landing_page String,
      landing_domain Nullable(String),
      landing_path Nullable(String),
      utm_source Nullable(String),
      utm_medium Nullable(String),
      utm_campaign Nullable(String),
      utm_term Nullable(String),
      utm_content Nullable(String),
      utm_id Nullable(String),
      utm_id_from Nullable(String),
      channel Nullable(String),
      screen_width Nullable(UInt16),
      screen_height Nullable(UInt16),
      viewport_width Nullable(UInt16),
      viewport_height Nullable(UInt16),
      device Nullable(String),
      browser Nullable(String),
      browser_type Nullable(String),
      os Nullable(String),
      user_agent Nullable(String),
      connection_type Nullable(String),
      language Nullable(String),
      timezone Nullable(String),
      max_scroll Nullable(UInt8),
      sdk_version Nullable(String),
      properties Map(String, String) DEFAULT map(),
      INDEX idx_workspace_id workspace_id TYPE bloom_filter GRANULARITY 1,
      INDEX idx_name name TYPE bloom_filter(0.01) GRANULARITY 1,
      INDEX idx_browser_type browser_type TYPE set(10) GRANULARITY 1
    ) ENGINE = MergeTree()
    PARTITION BY toYYYYMMDD(created_at)
    ORDER BY (workspace_id, session_id, created_at)
    TTL created_at + INTERVAL 7 DAY
  `,

  sessions: `
    CREATE TABLE IF NOT EXISTS {database}.sessions (
      id String,
      workspace_id String,
      created_at DateTime64(3),
      updated_at DateTime64(3),
      duration Nullable(UInt32),
      year UInt16,
      month UInt8,
      day UInt8,
      day_of_week UInt8,
      week_number UInt8,
      hour UInt8,
      is_weekend Bool,
      referrer Nullable(String),
      referrer_domain Nullable(String),
      referrer_path Nullable(String),
      is_direct Bool,
      landing_page String,
      landing_domain Nullable(String),
      landing_path Nullable(String),
      entry_page Nullable(String),
      exit_page Nullable(String),
      utm_source Nullable(String),
      utm_medium Nullable(String),
      utm_campaign Nullable(String),
      utm_term Nullable(String),
      utm_content Nullable(String),
      utm_id Nullable(String),
      utm_id_from Nullable(String),
      channel Nullable(String),
      screen_width Nullable(UInt16),
      screen_height Nullable(UInt16),
      viewport_width Nullable(UInt16),
      viewport_height Nullable(UInt16),
      user_agent Nullable(String),
      language Nullable(String),
      timezone Nullable(String),
      browser Nullable(String),
      browser_type Nullable(String),
      os Nullable(String),
      device Nullable(String),
      connection_type Nullable(String),
      max_scroll Nullable(UInt8),
      sdk_version Nullable(String),
      INDEX idx_workspace_id workspace_id TYPE bloom_filter GRANULARITY 1,
      INDEX idx_created_at created_at TYPE minmax GRANULARITY 1
    ) ENGINE = ReplacingMergeTree(updated_at)
    PARTITION BY toYYYYMM(created_at)
    ORDER BY (workspace_id, created_at, id)
  `,

  sessions_mv: `
    CREATE MATERIALIZED VIEW IF NOT EXISTS {database}.sessions_mv
    TO {database}.sessions AS
    SELECT
      session_id as id,
      workspace_id,
      min(events.created_at) as created_at,
      max(events.created_at) as updated_at,
      dateDiff('second', min(events.created_at), max(events.created_at)) as duration,
      argMin(toYear(events.created_at), events.created_at) as year,
      argMin(toMonth(events.created_at), events.created_at) as month,
      argMin(toDayOfMonth(events.created_at), events.created_at) as day,
      argMin(toDayOfWeek(events.created_at), events.created_at) as day_of_week,
      argMin(toWeek(events.created_at), events.created_at) as week_number,
      argMin(toHour(events.created_at), events.created_at) as hour,
      argMin(toDayOfWeek(events.created_at) IN (6, 7), events.created_at) as is_weekend,
      argMin(referrer, events.created_at) as referrer,
      argMin(referrer_domain, events.created_at) as referrer_domain,
      argMin(referrer_path, events.created_at) as referrer_path,
      argMin(is_direct, events.created_at) as is_direct,
      argMin(landing_page, events.created_at) as landing_page,
      argMin(landing_domain, events.created_at) as landing_domain,
      argMin(landing_path, events.created_at) as landing_path,
      argMin(path, events.created_at) as entry_page,
      argMax(path, events.created_at) as exit_page,
      argMin(utm_source, events.created_at) as utm_source,
      argMin(utm_medium, events.created_at) as utm_medium,
      argMin(utm_campaign, events.created_at) as utm_campaign,
      argMin(utm_term, events.created_at) as utm_term,
      argMin(utm_content, events.created_at) as utm_content,
      argMin(utm_id, events.created_at) as utm_id,
      argMin(utm_id_from, events.created_at) as utm_id_from,
      argMin(channel, events.created_at) as channel,
      any(screen_width) as screen_width,
      any(screen_height) as screen_height,
      any(viewport_width) as viewport_width,
      any(viewport_height) as viewport_height,
      any(user_agent) as user_agent,
      any(language) as language,
      any(timezone) as timezone,
      any(browser) as browser,
      any(browser_type) as browser_type,
      any(os) as os,
      any(device) as device,
      any(connection_type) as connection_type,
      max(max_scroll) as max_scroll,
      any(sdk_version) as sdk_version
    FROM {database}.events
    GROUP BY session_id, workspace_id
  `,
};
