// System schemas - stored in staminads_system database
export const SYSTEM_SCHEMAS: Record<string, string> = {
  workspaces: `
    CREATE TABLE IF NOT EXISTS {database}.workspaces (
      id String,
      name String,
      website String,
      timezone String,
      currency String,
      logo_url String DEFAULT '',
      timescore_reference UInt32 DEFAULT 60,
      bounce_threshold UInt32 DEFAULT 10,
      status Enum8('initializing' = 1, 'active' = 2, 'inactive' = 3, 'error' = 4),
      custom_dimensions String DEFAULT '[]',
      filters String DEFAULT '[]',
      geo_enabled Bool DEFAULT true,
      geo_store_city Bool DEFAULT true,
      geo_store_region Bool DEFAULT true,
      geo_coordinates_precision UInt8 DEFAULT 2,
      integrations String DEFAULT '[]',
      created_at DateTime64(3) DEFAULT now64(3),
      updated_at DateTime64(3) DEFAULT now64(3)
    ) ENGINE = MergeTree()
    ORDER BY id
  `,

  backfill_tasks: `
    CREATE TABLE IF NOT EXISTS {database}.backfill_tasks (
      id String,
      workspace_id String,
      status Enum8('pending' = 1, 'running' = 2, 'completed' = 3, 'failed' = 4, 'cancelled' = 5),
      lookback_days UInt16,
      chunk_size_days UInt8 DEFAULT 1,
      batch_size UInt32 DEFAULT 5000,
      total_sessions UInt64 DEFAULT 0,
      processed_sessions UInt64 DEFAULT 0,
      total_events UInt64 DEFAULT 0,
      processed_events UInt64 DEFAULT 0,
      current_date_chunk Nullable(Date),
      created_at DateTime64(3) DEFAULT now64(3),
      updated_at DateTime64(3) DEFAULT now64(3),
      started_at Nullable(DateTime64(3)),
      completed_at Nullable(DateTime64(3)),
      error_message String DEFAULT '',
      retry_count UInt8 DEFAULT 0,
      dimensions_snapshot String DEFAULT '[]',
      filters_snapshot String DEFAULT '[]'
    ) ENGINE = ReplacingMergeTree(updated_at)
    ORDER BY id
  `,
};

// Workspace schemas - stored in staminads_ws_{workspace_id} databases
// Note: workspace_id removed from ORDER BY and indexes since each database is per-workspace
export const WORKSPACE_SCHEMAS: Record<string, string> = {
  events: `
    CREATE TABLE IF NOT EXISTS {database}.events (
      id UUID DEFAULT generateUUIDv4(),
      session_id String,
      workspace_id String,
      received_at DateTime64(3),
      created_at DateTime64(3),
      updated_at DateTime64(3),
      name LowCardinality(String),
      path String,
      duration UInt64 DEFAULT 0,
      referrer String DEFAULT '',
      referrer_domain String DEFAULT '',
      referrer_path String DEFAULT '',
      is_direct Bool DEFAULT false,
      landing_page String,
      landing_domain String DEFAULT '',
      landing_path String DEFAULT '',
      utm_source String DEFAULT '',
      utm_medium String DEFAULT '',
      utm_campaign String DEFAULT '',
      utm_term String DEFAULT '',
      utm_content String DEFAULT '',
      utm_id String DEFAULT '',
      utm_id_from String DEFAULT '',
      channel LowCardinality(String) DEFAULT '',
      channel_group LowCardinality(String) DEFAULT '',
      stm_1 String DEFAULT '',
      stm_2 String DEFAULT '',
      stm_3 String DEFAULT '',
      stm_4 String DEFAULT '',
      stm_5 String DEFAULT '',
      stm_6 String DEFAULT '',
      stm_7 String DEFAULT '',
      stm_8 String DEFAULT '',
      stm_9 String DEFAULT '',
      stm_10 String DEFAULT '',
      screen_width UInt16 DEFAULT 0,
      screen_height UInt16 DEFAULT 0,
      viewport_width UInt16 DEFAULT 0,
      viewport_height UInt16 DEFAULT 0,
      device String DEFAULT '',
      browser String DEFAULT '',
      browser_type String DEFAULT '',
      os String DEFAULT '',
      user_agent String DEFAULT '',
      connection_type String DEFAULT '',
      language String DEFAULT '',
      timezone String DEFAULT '',
      country LowCardinality(String) DEFAULT '',
      region LowCardinality(String) DEFAULT '',
      city String DEFAULT '',
      latitude Nullable(Float32),
      longitude Nullable(Float32),
      max_scroll UInt8 DEFAULT 0,
      sdk_version String DEFAULT '',
      properties Map(String, String) DEFAULT map(),
      INDEX idx_name name TYPE bloom_filter(0.01) GRANULARITY 1,
      INDEX idx_browser_type browser_type TYPE set(10) GRANULARITY 1
    ) ENGINE = MergeTree()
    PARTITION BY toYYYYMMDD(received_at)
    ORDER BY (session_id, received_at)
    TTL toDateTime(received_at) + INTERVAL 7 DAY
  `,

  sessions: `
    CREATE TABLE IF NOT EXISTS {database}.sessions (
      id String,
      workspace_id String,
      created_at DateTime64(3),
      updated_at DateTime64(3),
      duration UInt32 DEFAULT 0,
      year UInt16,
      month UInt8,
      day UInt8,
      day_of_week UInt8,
      week_number UInt8,
      hour UInt8,
      is_weekend Bool,
      referrer String DEFAULT '',
      referrer_domain String DEFAULT '',
      referrer_path String DEFAULT '',
      is_direct Bool,
      landing_page String,
      landing_domain String DEFAULT '',
      landing_path String DEFAULT '',
      exit_path String DEFAULT '',
      utm_source String DEFAULT '',
      utm_medium String DEFAULT '',
      utm_campaign String DEFAULT '',
      utm_term String DEFAULT '',
      utm_content String DEFAULT '',
      utm_id String DEFAULT '',
      utm_id_from String DEFAULT '',
      channel LowCardinality(String) DEFAULT '',
      channel_group LowCardinality(String) DEFAULT '',
      stm_1 String DEFAULT '',
      stm_2 String DEFAULT '',
      stm_3 String DEFAULT '',
      stm_4 String DEFAULT '',
      stm_5 String DEFAULT '',
      stm_6 String DEFAULT '',
      stm_7 String DEFAULT '',
      stm_8 String DEFAULT '',
      stm_9 String DEFAULT '',
      stm_10 String DEFAULT '',
      screen_width UInt16 DEFAULT 0,
      screen_height UInt16 DEFAULT 0,
      viewport_width UInt16 DEFAULT 0,
      viewport_height UInt16 DEFAULT 0,
      user_agent String DEFAULT '',
      language String DEFAULT '',
      timezone String DEFAULT '',
      country LowCardinality(String) DEFAULT '',
      region LowCardinality(String) DEFAULT '',
      city String DEFAULT '',
      latitude Nullable(Float32),
      longitude Nullable(Float32),
      browser String DEFAULT '',
      browser_type String DEFAULT '',
      os String DEFAULT '',
      device String DEFAULT '',
      connection_type String DEFAULT '',
      max_scroll UInt8 DEFAULT 0,
      sdk_version String DEFAULT '',
      INDEX idx_created_at created_at TYPE minmax GRANULARITY 1
    ) ENGINE = ReplacingMergeTree(updated_at)
    PARTITION BY toYYYYMM(created_at)
    ORDER BY (created_at, id)
  `,

  sessions_mv: `
    CREATE MATERIALIZED VIEW IF NOT EXISTS {database}.sessions_mv
    TO {database}.sessions AS
    SELECT
      session_id as id,
      workspace_id,

      -- Use SDK timestamps (same for all events in session)
      any(created_at) as created_at,
      max(updated_at) as updated_at,
      max(duration) as duration,

      -- Derive time dimensions from SDK created_at
      any(toYear(created_at)) as year,
      any(toMonth(created_at)) as month,
      any(toDayOfMonth(created_at)) as day,
      any(toDayOfWeek(created_at)) as day_of_week,
      any(toWeek(created_at)) as week_number,
      any(toHour(created_at)) as hour,
      any(toDayOfWeek(created_at) IN (6, 7)) as is_weekend,

      -- Session-level fields (same for all events)
      any(referrer) as referrer,
      any(referrer_domain) as referrer_domain,
      any(referrer_path) as referrer_path,
      any(is_direct) as is_direct,
      any(landing_page) as landing_page,
      any(landing_domain) as landing_domain,
      any(landing_path) as landing_path,
      argMax(path, updated_at) as exit_path,
      any(utm_source) as utm_source,
      any(utm_medium) as utm_medium,
      any(utm_campaign) as utm_campaign,
      any(utm_term) as utm_term,
      any(utm_content) as utm_content,
      any(utm_id) as utm_id,
      any(utm_id_from) as utm_id_from,
      any(channel) as channel,
      any(channel_group) as channel_group,
      any(stm_1) as stm_1,
      any(stm_2) as stm_2,
      any(stm_3) as stm_3,
      any(stm_4) as stm_4,
      any(stm_5) as stm_5,
      any(stm_6) as stm_6,
      any(stm_7) as stm_7,
      any(stm_8) as stm_8,
      any(stm_9) as stm_9,
      any(stm_10) as stm_10,
      any(screen_width) as screen_width,
      any(screen_height) as screen_height,
      any(viewport_width) as viewport_width,
      any(viewport_height) as viewport_height,
      any(user_agent) as user_agent,
      any(language) as language,
      any(timezone) as timezone,
      any(country) as country,
      any(region) as region,
      any(city) as city,
      any(latitude) as latitude,
      any(longitude) as longitude,
      any(browser) as browser,
      any(browser_type) as browser_type,
      any(os) as os,
      any(device) as device,
      any(connection_type) as connection_type,
      max(max_scroll) as max_scroll,
      any(sdk_version) as sdk_version
    FROM {database}.events
    GROUP BY session_id, workspace_id
  `,
};
